# Generated by Django 3.2.10 on 2021-12-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_squashed_0003_alter_painting_inception_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='picture_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
