# Generated by Django 3.2.10 on 2021-12-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='creators',
            field=models.ManyToManyField(related_name='paintings', to='api.Creator'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='depicts',
            field=models.ManyToManyField(related_name='paintings', to='api.Depiction'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='genres',
            field=models.ManyToManyField(related_name='paintings', to='api.Genre'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='locations',
            field=models.ManyToManyField(related_name='paintings', to='api.Location'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='materials',
            field=models.ManyToManyField(related_name='paintings', to='api.Material'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='movements',
            field=models.ManyToManyField(related_name='paintings', to='api.Movement'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='picture_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
