version: '3.9'

services:
  db:
    container_name: db
    hostname: postgres
    image: postgres:latest
    env_file: &envfile
      - .env
    networks:
      - main
    ports:
      - '5432:5432'
    restart: on-failure
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  app:
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000 & watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A worker.worker.app worker --loglevel=INFO"
    container_name: app
    env_file: *envfile
    depends_on:
      - db
      - rabbitmq
    ports:
      - '8000:8000'
    hostname: app
    build: .
    image: &app app
    volumes:
      - ./app:/app
    networks:
      - main
    restart: on-failure

  rabbitmq:
      container_name: rabbitmq
      hostname: rabbitmq
      image: rabbitmq:3.8-alpine
      env_file: *envfile
      networks:
        - main
      ports:
        - '5672:5672'
        - '15672:15672'
      restart: on-failure

  flower:
    image: zoomeranalytics/flower:0.9.1-4.0.2
    container_name: flower
    hostname: flower
    restart: "no"
    env_file: *envfile
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
    networks:
      - main

networks:
  main:

volumes:
  postgresql-data:
